import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import Articles from "../components/Articles";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Hero from "../components/Hero";
import NavMenuMobile from "../components/NavMenuMobile";
import WhyUs from "../components/WhyUs";

const Home: NextPage = () => {
  const [navOpen, setNavOpen] = useState(false);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header navOpen={navOpen} setNavOpen={setNavOpen}></Header>
      <main>
        <Hero></Hero>
        {navOpen && <NavMenuMobile></NavMenuMobile>}
        <WhyUs></WhyUs>
        <Articles></Articles>
        <Footer />
      </main>
    </>
  );
};

export default Home;
